export type {
  Admin,
  Customer,
  CustomerOtp,
  PasswordResetOtp,
  Service,
  Barber,
  BarberService,
  BarberAvailability,
  Appointment,
  Payment,
  PaymentSetting,
  CheckoutSession,
  BarberEarning,
  BarberAssignmentHistory,
  CommissionRateHistory,
  BarberNotification,
  Gallery,
  Review,
  ContactMessage,
  ContactReply,
  Role,
  OtpPurpose,
  BarberType,
  CommissionType,
  AppointmentStatus,
  PaymentMethod,
  PaymentStatus,
  CheckoutSessionStatus,
  EarningStatus,
  AssignmentAction,
  BarberNotificationType,
  GalleryCategory,
  ReviewStatus,
  ContactMessageStatus,
  ContactReplyStatus,
} from '@prisma/client'

export {
  Role as RoleEnum,
  OtpPurpose as OtpPurposeEnum,
  BarberType as BarberTypeEnum,
  CommissionType as CommissionTypeEnum,
  AppointmentStatus as AppointmentStatusEnum,
  PaymentMethod as PaymentMethodEnum,
  PaymentStatus as PaymentStatusEnum,
  CheckoutSessionStatus as CheckoutSessionStatusEnum,
  EarningStatus as EarningStatusEnum,
  AssignmentAction as AssignmentActionEnum,
  BarberNotificationType as BarberNotificationTypeEnum,
  GalleryCategory as GalleryCategoryEnum,
  ReviewStatus as ReviewStatusEnum,
  ContactMessageStatus as ContactMessageStatusEnum,
  ContactReplyStatus as ContactReplyStatusEnum,
} from '@prisma/client'

export { prisma, prisma as db } from '../config/database'